// AUTO-GENERATED by export-course/app-data.mjs from blocks.json — do not hand-edit.
// Regenerate: node app-data.mjs [course-dir] [out-path]
window.TONGUES_COURSE = {
  "contract_version": 1,
  "id": "tongues-es-a1",
  "lang_pair": {
    "target": "es",
    "base": "en"
  },
  "meta": {
    "level": "A1",
    "title": "Saludos y presentaciones",
    "audience": "Adult beginner Spanish learners, optionally co-learning with a child",
    "objectives": [
      "Greet someone and say goodbye in Spanish, formally and informally",
      "Introduce yourself and ask someone's name",
      "Use basic politeness formulas (please, thank you, sorry, excuse me)",
      "Use 'senor/senora/senorita' and gendered nouns like 'amigo/amiga' with correct agreement"
    ]
  },
  "scene": {
    "setting": "park",
    "opening_line": "You're at the park. A new friend walks up — what do you say?",
    "closing_line": "Time to head home. One last exchange before you go.",
    "spine": {
      "target_q": "¿Cómo te llamas?",
      "en_q": "What's your name?",
      "target_a": "Me llamo…",
      "en_a": "My name is…"
    }
  },
  "units": [
    {
      "id": "unit-1-saludos",
      "title": "Saludos y presentaciones",
      "description": "Greetings and introductions -- the first unit of Tongues Spanish A1.",
      "objective": "Greet someone, introduce yourself, and say goodbye.",
      "lessons": [
        {
          "id": "lesson-saludos-01-hola",
          "dotted_id": "1.1",
          "title": "¡Hola! Saying hi",
          "summary": "The greeting words that open every Spanish conversation, plus yes and no.",
          "objective": "Greet someone appropriately for the time of day and answer yes or no.",
          "hook": "Every conversation you'll ever have in Spanish starts with one word.",
          "builds_on": null,
          "duration_minutes": 10,
          "block_ids": [
            "block-es-a1-hola-001",
            "block-es-a1-si-001",
            "block-es-a1-no-001",
            "block-es-a1-buenos-dias-001",
            "block-es-a1-buenas-tardes-001",
            "block-es-a1-buenas-noches-001",
            "block-es-a1-pattern-greetings-time-001"
          ]
        },
        {
          "id": "lesson-saludos-02-como-estas",
          "dotted_id": "1.2",
          "title": "¿Cómo estás? How are you?",
          "summary": "Ask how someone's doing and answer honestly — good, bad, or in between.",
          "objective": "Ask and answer ¿Cómo estás? using bien, mal, or más o menos.",
          "hook": "After hello, the next thing anyone asks is how you're doing.",
          "builds_on": "1.1",
          "duration_minutes": 8,
          "block_ids": [
            "block-es-a1-como-001",
            "block-es-a1-que-001",
            "block-es-a1-bien-001",
            "block-es-a1-mal-001",
            "block-es-a1-mas-o-menos-001",
            "block-es-a1-y-tu-001"
          ]
        },
        {
          "id": "lesson-saludos-03-nombres",
          "dotted_id": "1.3",
          "title": "¿Cómo te llamas? Names & introductions",
          "summary": "Trade names and say it's nice to meet someone — the spine phrase of the whole unit.",
          "objective": "Ask and give a name using ¿Cómo te llamas? / Me llamo…, and say mucho gusto.",
          "hook": "Once you know how someone's doing, the next question is always their name.",
          "builds_on": "1.2",
          "duration_minutes": 10,
          "block_ids": [
            "block-es-a1-yo-001",
            "block-es-a1-tu-001",
            "block-es-a1-ser-001",
            "block-es-a1-llamarse-001",
            "block-es-a1-mucho-gusto-001",
            "block-es-a1-encantado-001",
            "block-es-a1-encantada-001"
          ]
        },
        {
          "id": "lesson-saludos-04-amigos-personas",
          "dotted_id": "1.4",
          "title": "Amigos y mayores — Friends & grown-ups",
          "summary": "Meet your new friend AND their grown-up — the -o/-a friend pattern, and the polite words for adults.",
          "objective": "Use amigo/amiga correctly by gender, and address an adult politely with usted, señor, señora, or señorita.",
          "hook": "At the park, you don't just meet a kid — you meet their grown-up too.",
          "builds_on": "1.3",
          "duration_minutes": 9,
          "block_ids": [
            "block-es-a1-amigo-001",
            "block-es-a1-amiga-001",
            "block-es-a1-pattern-gender-oa-001",
            "block-es-a1-usted-001",
            "block-es-a1-senor-001",
            "block-es-a1-senora-001",
            "block-es-a1-senorita-001"
          ]
        },
        {
          "id": "lesson-saludos-05-cortesia",
          "dotted_id": "1.5",
          "title": "Por favor y gracias — Being polite",
          "summary": "The everyday courtesy words: please, thanks, you're welcome, sorry, and excuse me.",
          "objective": "Use por favor, gracias, de nada, lo siento, perdón, and disculpe appropriately.",
          "hook": "Politeness is half of any language — these six words carry you through almost any bump in the road.",
          "builds_on": "1.4",
          "duration_minutes": 8,
          "block_ids": [
            "block-es-a1-por-favor-001",
            "block-es-a1-gracias-001",
            "block-es-a1-de-nada-001",
            "block-es-a1-lo-siento-001",
            "block-es-a1-perdon-001",
            "block-es-a1-disculpe-001"
          ]
        },
        {
          "id": "lesson-saludos-06-adios",
          "dotted_id": "1.6",
          "title": "Adiós — Saying goodbye",
          "summary": "Every way to say goodbye, and one full conversation putting the whole unit together.",
          "objective": "Say goodbye appropriately and perform the full greet-to-farewell exchange.",
          "hook": "Every good conversation needs a good ending.",
          "builds_on": "1.5",
          "duration_minutes": 8,
          "block_ids": [
            "block-es-a1-adios-001",
            "block-es-a1-hasta-luego-001",
            "block-es-a1-hasta-pronto-001",
            "block-es-a1-hasta-manana-001",
            "block-es-a1-capstone-nuevo-amigo-001"
          ]
        }
      ]
    }
  ],
  "blocks": {
    "block-es-a1-hola-001": {
      "id": "block-es-a1-hola-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 0,
      "content": "“hola” — hi. The single most useful word in Spanish — every conversation can start here.",
      "learning_objective": "Learner recognizes and can use \"hola\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Hola means “hi!” It's the very first word you'll use to say hello to a new friend. Try it: wave and say ¡Hola! with your grown-up!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "hola",
        "translation": "Hi",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈo.la/",
        "audio": "audio/hola-001-lemma.mp3",
        "audio_example": "audio/hola-001-example.mp3",
        "freq_rank": 1138,
        "cefr": "A1",
        "example": {
          "target": "Hola.",
          "en": "Hi."
        }
      },
      "distractors": [
        {
          "lemma": "adiós",
          "translation": "Bye",
          "gender": null
        },
        {
          "lemma": "hasta pronto",
          "translation": "See you soon",
          "gender": null
        },
        {
          "lemma": "buenas tardes",
          "translation": "Good afternoon",
          "gender": null
        }
      ]
    },
    "block-es-a1-si-001": {
      "id": "block-es-a1-si-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 1,
      "content": "“sí” — yes. Note the accent mark — without it, si means “if.”",
      "learning_objective": "Learner recognizes and can use \"sí\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Sí means “yes!” Nod your head when you say it.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "sí",
        "translation": "Yes",
        "pos": "adv",
        "gender": null,
        "ipa": "/si/",
        "audio": "audio/si-001-lemma.mp3",
        "audio_example": "audio/si-001-example.mp3",
        "freq_rank": 174,
        "cefr": "A1",
        "example": {
          "target": "¿Ah, sí?",
          "en": "Is that right?"
        }
      },
      "distractors": [
        {
          "lemma": "cómo",
          "translation": "How",
          "gender": null
        },
        {
          "lemma": "bien",
          "translation": "Fine",
          "gender": null
        },
        {
          "lemma": "más o menos",
          "translation": "More or less",
          "gender": null
        }
      ]
    },
    "block-es-a1-no-001": {
      "id": "block-es-a1-no-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 2,
      "content": "“no” — no. The all-purpose negative — pairs with almost anything: No puedo. = I can't.",
      "learning_objective": "Learner recognizes and can use \"no\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "No means “no.” Shake your head when you say it.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "no",
        "translation": "No",
        "pos": "adv",
        "gender": null,
        "ipa": "/no/",
        "audio": "audio/no-001-lemma.mp3",
        "audio_example": "audio/no-001-example.mp3",
        "freq_rank": 7,
        "cefr": "A1",
        "example": {
          "target": "No puedo.",
          "en": "I can't."
        }
      },
      "distractors": [
        {
          "lemma": "sí",
          "translation": "Yes",
          "gender": null
        },
        {
          "lemma": "más o menos",
          "translation": "More or less",
          "gender": null
        },
        {
          "lemma": "mal",
          "translation": "Bad / Badly",
          "gender": null
        }
      ]
    },
    "block-es-a1-buenos-dias-001": {
      "id": "block-es-a1-buenos-dias-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 3,
      "content": "“buenos días” — good morning. Use it from waking up until roughly midday.",
      "learning_objective": "Learner recognizes and can use \"buenos días\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Buenos días means “good morning” — say it when you first see someone in the morning.",
      "mnemonic": null,
      "usage_note": "Use roughly from waking up until midday/lunchtime. Greeting only — it doesn't double as a farewell.",
      "lang": {
        "lemma": "buenos días",
        "translation": "Good morning",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈbwe.nos ˈdi.as/",
        "audio": "audio/buenos-dias-001-lemma.mp3",
        "audio_example": "audio/buenos-dias-001-example.mp3",
        "freq_rank": 3886,
        "cefr": "A1",
        "example": {
          "target": "Buenos días, Tom.",
          "en": "Good morning, Tom."
        }
      },
      "distractors": [
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        },
        {
          "lemma": "hola",
          "translation": "Hi",
          "gender": null
        },
        {
          "lemma": "de nada",
          "translation": "You're welcome",
          "gender": null
        }
      ]
    },
    "block-es-a1-buenas-tardes-001": {
      "id": "block-es-a1-buenas-tardes-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 4,
      "content": "“buenas tardes” — good afternoon. Use it from midday into early evening; once it starts getting dark, switch to buenas noches.",
      "learning_objective": "Learner recognizes and can use \"buenas tardes\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Buenas tardes means “good afternoon” — say it once it's past lunchtime but still light out.",
      "mnemonic": null,
      "usage_note": "Use from midday into early evening — roughly once lunch is behind you until it starts getting dark. Greeting only — it doesn't double as a farewell.",
      "lang": {
        "lemma": "buenas tardes",
        "translation": "Good afternoon",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈbwe.nas ˈtaɾ.ðes/",
        "audio": "audio/buenas-tardes-001-lemma.mp3",
        "audio_example": "audio/buenas-tardes-001-example.mp3",
        "freq_rank": 12023,
        "cefr": "A1",
        "example": {
          "target": "Buenas tardes, ¿cómo estás?",
          "en": "Good afternoon, how are you?"
        }
      },
      "distractors": [
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "gracias",
          "translation": "Thanks",
          "gender": null
        },
        {
          "lemma": "hasta luego",
          "translation": "See you",
          "gender": null
        }
      ]
    },
    "block-es-a1-buenas-noches-001": {
      "id": "block-es-a1-buenas-noches-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 5,
      "content": "“buenas noches” — good evening / goodnight. The only greeting in this set that doubles as a farewell.",
      "learning_objective": "Learner recognizes and can use \"buenas noches\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Buenas noches means “good evening” at night — and it also means “goodnight” when it's time for bed! Try it: give your grown-up a goodnight wave and say ¡Buenas noches!",
      "mnemonic": null,
      "usage_note": "Use once it's evening or night. Unlike buenos días/buenas tardes, buenas noches does double duty — it works as both a greeting (“good evening”) and a farewell (“goodnight”).",
      "lang": {
        "lemma": "buenas noches",
        "translation": "Goodnight",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈbwe.nas ˈno.tʃes/",
        "audio": "audio/buenas-noches-001-lemma.mp3",
        "audio_example": "audio/buenas-noches-001-example.mp3",
        "freq_rank": 5520,
        "cefr": "A1",
        "example": {
          "target": "Buenas noches, Tom.",
          "en": "Good night, Tom."
        }
      },
      "distractors": [
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "hasta mañana",
          "translation": "See you tomorrow",
          "gender": null
        },
        {
          "lemma": "disculpe",
          "translation": "Excuse me",
          "gender": null
        }
      ]
    },
    "block-es-a1-pattern-greetings-time-001": {
      "id": "block-es-a1-pattern-greetings-time-001",
      "type": "pattern_card",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-01-hola",
      "dotted_id": "1.1",
      "order_index": 6,
      "content": "Spanish greets by time of day, not just formality: buenos días, buenas tardes, and buenas noches each own a different part of the day, and buenas noches also doubles as “goodnight.”",
      "learning_objective": "Learner selects the correct time-of-day greeting (buenos días / buenas tardes / buenas noches) and recognizes buenas noches also functions as “goodnight.”",
      "difficulty": 1,
      "audience": "both",
      "flashcard": false,
      "games": [
        "quiz"
      ],
      "kid_track": "Spanish has a different greeting for each part of the day! Buenos días in the morning. Buenas tardes in the afternoon. Buenas noches at night — and you can also say buenas noches when it's time for bed, just like “goodnight!”",
      "mnemonic": null,
      "usage_note": null,
      "distractors": [],
      "pattern_card": {
        "id": "pattern-es-a1-greetings-time",
        "rule": "Spanish greets differently depending on the time of day, not just how formal you're being. Use buenos días roughly from waking up until midday. Use buenas tardes from midday into early evening, roughly once lunch is behind you until it starts getting dark. Use buenas noches once it's evening or night — and unlike the other two, buenas noches also works as a farewell (“goodnight”), not just a greeting. Exact cutoffs vary by region and person — treat these as “morning / afternoon / evening-night,” not an exact clock. (Optional, for the curious: días is grammatically masculine, which is why it pairs with buenos, while tardes and noches are grammatically feminine and pair with buenas — You'll meet this same masculine/feminine pattern again with the amigo/amiga pattern card later in the unit — here it's just applied to time-of-day nouns instead of people. This isn't about anything being literally male or female — it's just a grammar category Spanish nouns have.)",
        "visual_spec": "[buenos:MASC-blue] [días:MASC-blue] (morning)   [buenas:FEM-pink] [tardes:FEM-pink] (afternoon)   [buenas:FEM-pink] [noches:FEM-pink] (evening/night — also “goodnight”)",
        "examples": [
          {
            "target": "¡Buenos días!",
            "en": "Good morning!"
          },
          {
            "target": "Buenas tardes, señora.",
            "en": "Good afternoon, ma'am."
          },
          {
            "target": "Buenas noches, hasta mañana.",
            "en": "Goodnight, see you tomorrow."
          }
        ],
        "audience": "both"
      },
      "retrieval_game": {
        "id": "game-es-a1-pattern-greetings-time-quiz-001",
        "type": "quiz",
        "data": {
          "question": "It's 3 in the afternoon. Which greeting fits best?",
          "options": [
            "Buenos días",
            "Buenas tardes",
            "Buenas noches"
          ],
          "correct_index": 1
        }
      }
    },
    "block-es-a1-como-001": {
      "id": "block-es-a1-como-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 7,
      "content": "“cómo” — how. Opens two very common questions: ¿Cómo estás? (How are you?) and ¿Cómo te llamas? (What's your name? — literally “how do you call yourself”).",
      "learning_objective": "Learner recognizes and can use \"cómo\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Cómo means “how” — it's the little word that starts ¿Cómo estás? (How are you?) and ¿Cómo te llamas? (What's your name?). Try it: ask your grown-up ¿Cómo estás? and see what they say!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "cómo",
        "translation": "How",
        "pos": "adv",
        "gender": null,
        "ipa": "/ˈko.mo/",
        "audio": "audio/como-001-lemma.mp3",
        "audio_example": "audio/como-001-example.mp3",
        "freq_rank": 78,
        "cefr": "A1",
        "example": {
          "target": "¿Cómo estás?",
          "en": "How are you?"
        }
      },
      "distractors": [
        {
          "lemma": "bien",
          "translation": "Fine",
          "gender": null
        },
        {
          "lemma": "más o menos",
          "translation": "More or less",
          "gender": null
        },
        {
          "lemma": "sí",
          "translation": "Yes",
          "gender": null
        }
      ]
    },
    "block-es-a1-que-001": {
      "id": "block-es-a1-que-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 8,
      "content": "“qué” — what. The go-to question word for asking about a thing: ¿Qué es esto? = What is this?",
      "learning_objective": "Learner recognizes and can use \"qué\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Qué means “what” — the word you use to ask about something, like ¿Qué es esto? (What is this?). Try it: ask your grown-up ¿Qué es esto? about a toy!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "qué",
        "translation": "What",
        "pos": "pron",
        "gender": null,
        "ipa": "/ke/",
        "audio": "audio/que-001-lemma.mp3",
        "audio_example": "audio/que-001-example.mp3",
        "freq_rank": 25,
        "cefr": "A1",
        "example": {
          "target": "¿Qué es esto?",
          "en": "What is this?"
        }
      },
      "distractors": [
        {
          "lemma": "yo",
          "translation": "I",
          "gender": null
        },
        {
          "lemma": "tú",
          "translation": "You (informal)",
          "gender": null
        },
        {
          "lemma": "usted",
          "translation": "You (formal)",
          "gender": null
        }
      ]
    },
    "block-es-a1-bien-001": {
      "id": "block-es-a1-bien-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 9,
      "content": "“bien” — fine / good / well, depending on context. Bien. answers ¿Cómo estás?; Está bien. = It's good/okay.",
      "learning_objective": "Learner recognizes and can use \"bien\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Bien means “good” or “fine” — you'll hear it a lot when someone asks ¿Cómo estás? (How are you?) and you answer ¡Bien! (Good!)",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "bien",
        "translation": "Fine",
        "pos": "adv",
        "gender": null,
        "ipa": "/ˈbjen/",
        "audio": "audio/bien-001-lemma.mp3",
        "audio_example": "audio/bien-001-example.mp3",
        "freq_rank": 65,
        "cefr": "A1",
        "example": {
          "target": "Está bien.",
          "en": "It's good."
        }
      },
      "distractors": [
        {
          "lemma": "mal",
          "translation": "Bad / Badly",
          "gender": null
        },
        {
          "lemma": "no",
          "translation": "No",
          "gender": null
        },
        {
          "lemma": "cómo",
          "translation": "How",
          "gender": null
        }
      ]
    },
    "block-es-a1-mal-001": {
      "id": "block-es-a1-mal-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 10,
      "content": "“mal” — bad / badly. The opposite of bien; ¿Está mal? = Is that wrong?",
      "learning_objective": "Learner recognizes and can use \"mal\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Mal means “bad” — the opposite of bien. If ¿Cómo estás? catches you on a rough day, Mal is how you'd answer.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "mal",
        "translation": "Bad / Badly",
        "pos": "adv",
        "gender": null,
        "ipa": "/mal/",
        "audio": "audio/mal-001-lemma.mp3",
        "audio_example": "audio/mal-001-example.mp3",
        "freq_rank": 203,
        "cefr": "A1",
        "example": {
          "target": "Está mal.",
          "en": "It's wrong."
        }
      },
      "distractors": [
        {
          "lemma": "sí",
          "translation": "Yes",
          "gender": null
        },
        {
          "lemma": "más o menos",
          "translation": "More or less",
          "gender": null
        },
        {
          "lemma": "cómo",
          "translation": "How",
          "gender": null
        }
      ]
    },
    "block-es-a1-mas-o-menos-001": {
      "id": "block-es-a1-mas-o-menos-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 11,
      "content": "“más o menos” — more or less. The honest middle answer between sí and no: “¿Entendiste?” “Más o menos.” = “Did you understand?” “More or less.”",
      "learning_objective": "Learner recognizes and can use \"más o menos\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Más o menos means “so-so” or “kind of” — the perfect in-between answer for when you're not great and not bad, just okay.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "más o menos",
        "translation": "More or less",
        "pos": "adv",
        "gender": null,
        "ipa": "/ˈmas o ˈme.nos/",
        "audio": "audio/mas-o-menos-001-lemma.mp3",
        "audio_example": "audio/mas-o-menos-001-example.mp3",
        "freq_rank": 2066,
        "cefr": "A1",
        "example": {
          "target": "\"¿Entendiste?\" \"Más o menos.\"",
          "en": "\"Did you understand?\" \"More or less.\""
        }
      },
      "distractors": [
        {
          "lemma": "cómo",
          "translation": "How",
          "gender": null
        },
        {
          "lemma": "sí",
          "translation": "Yes",
          "gender": null
        },
        {
          "lemma": "bien",
          "translation": "Fine",
          "gender": null
        }
      ]
    },
    "block-es-a1-y-tu-001": {
      "id": "block-es-a1-y-tu-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-02-como-estas",
      "dotted_id": "1.2",
      "order_index": 12,
      "content": "“¿Y tú?” — and you? The bounce-back: after you answer a question, toss it right back. Bien, gracias. ¿Y tú? = Fine, thanks. And you?",
      "learning_objective": "Learner bounces a question back with ¿Y tú? right after answering it themselves.",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [],
      "kid_track": "¿Y tú? means “And you?” — it's how you ask the question right back! Someone says ¿Cómo estás? and you answer Bien, gracias. ¿Y tú? — now it's their turn to answer too.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "y tú",
        "translation": "And you?",
        "pos": "interj",
        "gender": null,
        "ipa": "/i ˈtu/",
        "audio": "audio/y-tu-001-lemma.mp3",
        "audio_example": "audio/y-tu-001-example.mp3",
        "freq_rank": 1745,
        "cefr": "A1",
        "example": {
          "target": "Bien, gracias. ¿Y tú?",
          "en": "Fine, thanks. And you?"
        }
      },
      "distractors": [
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "por favor",
          "translation": "Please",
          "gender": null
        },
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        }
      ]
    },
    "block-es-a1-yo-001": {
      "id": "block-es-a1-yo-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 13,
      "content": "“yo” — I. The subject pronoun for yourself — often dropped in Spanish since the verb ending already signals “I,” so yo mainly shows up for emphasis or as a one-word answer.",
      "learning_objective": "Learner recognizes and can use \"yo\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Yo means “I” — it's you, talking about yourself! Try it: point to yourself and say ¡Yo! when someone asks who did something.",
      "mnemonic": null,
      "usage_note": "Spanish usually drops subject pronouns (the verb ending already shows who's speaking), so yo mainly appears for emphasis or contrast (Yo sí quiero. = I do want to), or alone as a one-word answer to “¿Quién?” (Who?) — functioning like English “Me!” (Soy yo. = It's me.).",
      "lang": {
        "lemma": "yo",
        "translation": "I",
        "pos": "pron",
        "gender": null,
        "ipa": "/ʝo/",
        "audio": "audio/yo-001-lemma.mp3",
        "audio_example": "audio/yo-001-example.mp3",
        "freq_rank": 36,
        "cefr": "A1",
        "example": {
          "target": "Soy yo.",
          "en": "It's me."
        }
      },
      "distractors": [
        {
          "lemma": "qué",
          "translation": "What",
          "gender": null
        },
        {
          "lemma": "tú",
          "translation": "You (informal)",
          "gender": null
        },
        {
          "lemma": "usted",
          "translation": "You (formal)",
          "gender": null
        }
      ]
    },
    "block-es-a1-tu-001": {
      "id": "block-es-a1-tu-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 14,
      "content": "“tú” — you (informal). The everyday “you” for friends, family, and kids.",
      "learning_objective": "Learner recognizes and can use \"tú\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Tú is the easy, everyday word for “you” — the one you use with friends, family, and other kids. Try it: point to a friend and say ¡Tú! (You!)",
      "mnemonic": "Picture tú as the “close friend” word — a hug-distance you. Its formal counterpart, usted, is the “handshake with a stranger” word — arm's-length and polite.",
      "usage_note": "Informal “you.” Use with friends, family, kids, and peers — the default with anyone you're on familiar terms with. Heads up: some countries (Argentina, Uruguay, parts of Central America) use a different informal “you,” vos, instead of or alongside tú — you'll meet voseo in a later unit.",
      "lang": {
        "lemma": "tú",
        "translation": "You (informal)",
        "pos": "pron",
        "gender": null,
        "ipa": "/tu/",
        "audio": "audio/tu-001-lemma.mp3",
        "audio_example": "audio/tu-001-example.mp3",
        "freq_rank": 101,
        "cefr": "A1",
        "example": {
          "target": "¿Eres tú?",
          "en": "Is that you?"
        }
      },
      "distractors": [
        {
          "lemma": "qué",
          "translation": "What",
          "gender": null
        },
        {
          "lemma": "usted",
          "translation": "You (formal)",
          "gender": null
        },
        {
          "lemma": "yo",
          "translation": "I",
          "gender": null
        }
      ]
    },
    "block-es-a1-ser-001": {
      "id": "block-es-a1-ser-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 15,
      "content": "“ser” — to be. One of two Spanish verbs for “to be” (you'll meet the other, estar, in a later unit); ser covers identity and characteristics, like Soy... (I am...).",
      "learning_objective": "Learner recognizes and can use \"ser\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Try it: Soy... and then say your name! That's another way to answer ¿Cómo te llamas?",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "ser",
        "translation": "To be",
        "pos": "v",
        "gender": null,
        "ipa": "/seɾ/",
        "audio": "audio/ser-001-lemma.mp3",
        "audio_example": "audio/ser-001-example.mp3",
        "freq_rank": 7,
        "cefr": "A1",
        "example": {
          "target": "¿Eres tú?",
          "en": "Is that you?"
        }
      },
      "distractors": [
        {
          "lemma": "llamarse",
          "translation": "To be called",
          "gender": null
        },
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        },
        {
          "lemma": "sí",
          "translation": "Yes",
          "gender": null
        }
      ]
    },
    "block-es-a1-llamarse-001": {
      "id": "block-es-a1-llamarse-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 16,
      "content": "“llamarse” — to be called (literally, “to call oneself”). Used to ask and give names: ¿Cómo te llamas? = What is your name?",
      "learning_objective": "Learner recognizes and can use \"llamarse\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Llamarse is how you say your name in Spanish. ¿Cómo te llamas? means “What's your name?” and Me llamo... means “My name is...”",
      "mnemonic": "Llamarse looks like llama (the animal) — picture calling a llama by name to remember it means “to be called.” (Just a sound-alike trick — llamarse has nothing to do with llamas!)",
      "usage_note": null,
      "lang": {
        "lemma": "llamarse",
        "translation": "To be called",
        "pos": "v",
        "gender": null,
        "ipa": "/ʝaˈmaɾ.se/",
        "audio": "audio/llamarse-001-lemma.mp3",
        "audio_example": "audio/llamarse-001-example.mp3",
        "freq_rank": 474,
        "cefr": "A1",
        "example": {
          "target": "¿Cómo te llamas?",
          "en": "What is your name?"
        }
      },
      "distractors": [
        {
          "lemma": "ser",
          "translation": "To be",
          "gender": null
        },
        {
          "lemma": "tú",
          "translation": "You (informal)",
          "gender": null
        },
        {
          "lemma": "encantada",
          "translation": "Nice to meet you",
          "gender": "f"
        }
      ]
    },
    "block-es-a1-mucho-gusto-001": {
      "id": "block-es-a1-mucho-gusto-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 17,
      "content": "“mucho gusto” — nice to meet you. Say it right after trading names for the first time.",
      "learning_objective": "Learner recognizes and can use \"mucho gusto\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Mucho gusto means “nice to meet you!” — say it right after you both answer ¿Cómo te llamas? and Me llamo... Try it: shake hands (or high-five!) with your grown-up and say ¡Mucho gusto!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "mucho gusto",
        "translation": "Nice to meet you",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈmu.tʃo ˈɡus.to/",
        "audio": "audio/mucho-gusto-001-lemma.mp3",
        "audio_example": "audio/mucho-gusto-001-example.mp3",
        "freq_rank": 21655,
        "cefr": "A1",
        "example": {
          "target": "¡Mucho gusto conocerte!",
          "en": "It's nice to meet you."
        }
      },
      "distractors": [
        {
          "lemma": "lo siento",
          "translation": "Sorry",
          "gender": null
        },
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "por favor",
          "translation": "Please",
          "gender": null
        }
      ]
    },
    "block-es-a1-encantado-001": {
      "id": "block-es-a1-encantado-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 18,
      "content": "“encantado” — nice to meet you, said by a man or boy. (A woman or girl says encantada.)",
      "learning_objective": "Learner recognizes and can use \"encantado\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Encantado is what a boy or man says after meeting someone new — it means “nice to meet you!” Try it: shake hands (or high-five!) with your grown-up and say ¡Encantado!",
      "mnemonic": "Encantado/encantada shares a root with English “enchanted” — you're literally saying you're enchanted to meet them.",
      "usage_note": null,
      "lang": {
        "lemma": "encantado",
        "translation": "Nice to meet you",
        "pos": "adj",
        "gender": "m",
        "ipa": "/eŋ.kanˈta.ðo/",
        "audio": "audio/encantado-001-lemma.mp3",
        "audio_example": "audio/encantado-001-example.mp3",
        "freq_rank": 3741,
        "cefr": "A1",
        "example": {
          "target": "Encantado de conocerte.",
          "en": "Nice to meet you."
        }
      },
      "distractors": [
        {
          "lemma": "encantada",
          "translation": "Nice to meet you",
          "gender": "f"
        },
        {
          "lemma": "por favor",
          "translation": "Please",
          "gender": null
        },
        {
          "lemma": "de nada",
          "translation": "You're welcome",
          "gender": null
        }
      ]
    },
    "block-es-a1-encantada-001": {
      "id": "block-es-a1-encantada-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-03-nombres",
      "dotted_id": "1.3",
      "order_index": 19,
      "content": "“encantada” — nice to meet you, said by a woman or girl. (A man or boy says encantado.)",
      "learning_objective": "Learner recognizes and can use \"encantada\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Encantada is what a girl or woman says after meeting someone new — it means “nice to meet you!” Try it: shake hands (or high-five!) with your grown-up and say ¡Encantada!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "encantada",
        "translation": "Nice to meet you",
        "pos": "adj",
        "gender": "f",
        "ipa": "/eŋ.kanˈta.ða/",
        "audio": "audio/encantada-001-lemma.mp3",
        "audio_example": "audio/encantada-001-example.mp3",
        "freq_rank": 7766,
        "cefr": "A1",
        "example": {
          "target": "Encantada de conocerte.",
          "en": "Pleased to meet you."
        }
      },
      "distractors": [
        {
          "lemma": "encantado",
          "translation": "Nice to meet you",
          "gender": "m"
        },
        {
          "lemma": "hasta mañana",
          "translation": "See you tomorrow",
          "gender": null
        },
        {
          "lemma": "ser",
          "translation": "To be",
          "gender": null
        }
      ]
    },
    "block-es-a1-amigo-001": {
      "id": "block-es-a1-amigo-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 20,
      "content": "“amigo” — friend (male, or a mixed/general group). Its feminine form, amiga, means friend (female).",
      "learning_objective": "Learner recognizes and can use \"amigo\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Amigo means a friend who's a boy. If your new friend at the park is a boy, he's tu amigo!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "amigo",
        "translation": "Friend",
        "pos": "n",
        "gender": "m",
        "ipa": "/aˈmi.ɣo/",
        "audio": "audio/amigo-001-lemma.mp3",
        "audio_example": "audio/amigo-001-example.mp3",
        "freq_rank": 108,
        "cefr": "A1",
        "example": {
          "target": "¿Son amigos?",
          "en": "Are they friends?"
        }
      },
      "distractors": [
        {
          "lemma": "señor",
          "translation": "Sir",
          "gender": "m"
        },
        {
          "lemma": "señorita",
          "translation": "Miss",
          "gender": "f"
        },
        {
          "lemma": "señora",
          "translation": "Ma'am",
          "gender": "f"
        }
      ]
    },
    "block-es-a1-amiga-001": {
      "id": "block-es-a1-amiga-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 21,
      "content": "“amiga” — friend (female). Its masculine form, amigo, means friend (male, or a mixed/general group).",
      "learning_objective": "Learner recognizes and can use \"amiga\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Amiga means a friend who's a girl. If your new friend at the park is a girl, she's tu amiga!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "amiga",
        "translation": "Friend",
        "pos": "n",
        "gender": "f",
        "ipa": "/aˈmi.ɣa/",
        "audio": "audio/amiga-001-lemma.mp3",
        "audio_example": "audio/amiga-001-example.mp3",
        "freq_rank": 568,
        "cefr": "A1",
        "example": {
          "target": "¿Somos amigas?",
          "en": "Are we friends?"
        }
      },
      "distractors": [
        {
          "lemma": "señora",
          "translation": "Ma'am",
          "gender": "f"
        },
        {
          "lemma": "señorita",
          "translation": "Miss",
          "gender": "f"
        },
        {
          "lemma": "amigo",
          "translation": "Friend",
          "gender": "m"
        }
      ]
    },
    "block-es-a1-pattern-gender-oa-001": {
      "id": "block-es-a1-pattern-gender-oa-001",
      "type": "pattern_card",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 22,
      "content": "Masculine and feminine forms of Spanish words that describe people usually differ by their last letter — most swap -o for -a, and a few add -a to a consonant ending. Watch the ending to tell who's being talked about.",
      "learning_objective": "Learner recognizes the masculine/feminine -o/-a pattern in person-referring Spanish words (amigo/amiga, señor/señora, encantado/encantada) and selects the correct form.",
      "difficulty": 1,
      "audience": "both",
      "flashcard": false,
      "games": [
        "fill-blank"
      ],
      "kid_track": "Lots of Spanish words do this swap — but not every one, so keep listening too! Amigo (ends in an “oh” sound) is a friend who's a boy. Amiga (ends in an “ah” sound) is a friend who's a girl. Swap the last sound, and you swap who you mean!",
      "mnemonic": null,
      "usage_note": null,
      "distractors": [],
      "pattern_card": {
        "id": "pattern-es-a1-gender-oa",
        "rule": "Many Spanish words that describe people come in a masculine form and a feminine form. Most of the time the pattern is simple: the masculine form ends in -o, and the feminine form swaps that -o for -a — amigo becomes amiga, encantado becomes encantada. When the masculine form ends in a consonant instead of -o, the feminine form is usually made by adding -a — señor becomes señora. This pattern is common but not universal: some Spanish words that describe people don't change at all, so treat this as “most,” not “all.”",
        "visual_spec": "amig[o:MASC-blue] ↔ amig[a:FEM-pink]   señor[Ø:MASC-blue] ↔ señor[a:FEM-pink]   encantad[o:MASC-blue] ↔ encantad[a:FEM-pink]",
        "examples": [
          {
            "target": "Es mi amigo.",
            "en": "He's my friend."
          },
          {
            "target": "Es mi amiga.",
            "en": "She's my friend."
          },
          {
            "target": "Encantado.",
            "en": "Nice to meet you. (said by a man)"
          },
          {
            "target": "Encantada.",
            "en": "Nice to meet you. (said by a woman)"
          }
        ],
        "audience": "both"
      },
      "retrieval_game": {
        "id": "game-es-a1-pattern-gender-oa-cloze-001",
        "type": "fill-blank",
        "data": {
          "template": "Amig___ — she's my friend.",
          "blanks": [
            "a"
          ],
          "answer": "amiga"
        }
      }
    },
    "block-es-a1-usted-001": {
      "id": "block-es-a1-usted-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 23,
      "content": "“usted” — you (formal). The respectful “you” for strangers, elders, and anyone you'd address politely.",
      "learning_objective": "Learner recognizes and can use \"usted\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Usted is the extra-polite “you” — you'd use it with a teacher, or a grown-up you just met, like your friend's mom or dad. Try it: ¿Cómo está usted? — ask a grown-up how they are, extra-politely.",
      "mnemonic": "Picture usted as the “handshake with a stranger” word — arm's-length and polite. Its informal counterpart, tú, is the “close friend” word — hug-distance and casual.",
      "usage_note": "Formal, respectful “you.” Use with strangers, elders, and authority figures. Regional note: in Costa Rica and parts of Colombia and Ecuador, usted (not tú) is the everyday default even among close friends and family — a pattern called ustedeo; elsewhere in Latin America and Spain, usted stays reserved for formal/unfamiliar contexts. When addressing an adult you don't know, usted is the safer default anywhere.",
      "lang": {
        "lemma": "usted",
        "translation": "You (formal)",
        "pos": "pron",
        "gender": null,
        "ipa": "/usˈteð/",
        "audio": "audio/usted-001-lemma.mp3",
        "audio_example": "audio/usted-001-example.mp3",
        "freq_rank": 123,
        "cefr": "A1",
        "example": {
          "target": "¿Es usted?",
          "en": "Is that you?"
        }
      },
      "distractors": [
        {
          "lemma": "yo",
          "translation": "I",
          "gender": null
        },
        {
          "lemma": "qué",
          "translation": "What",
          "gender": null
        },
        {
          "lemma": "tú",
          "translation": "You (informal)",
          "gender": null
        }
      ]
    },
    "block-es-a1-senor-001": {
      "id": "block-es-a1-senor-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 24,
      "content": "“señor” — sir, or Mr. before a name. The respectful way to address or refer to a man.",
      "learning_objective": "Learner recognizes and can use \"señor\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Señor is the polite word for a man you just met — like your friend's dad.",
      "mnemonic": null,
      "usage_note": "Also doubles as a title before a surname, like “Mr.” (señor García = Mr. García). As a stand-alone term of address it's simply the respectful, everyday way to address or refer to a man — not stiff or old-fashioned.",
      "lang": {
        "lemma": "señor",
        "translation": "Sir",
        "pos": "n",
        "gender": "m",
        "ipa": "/seˈɲoɾ/",
        "audio": "audio/senor-001-lemma.mp3",
        "audio_example": "audio/senor-001-example.mp3",
        "freq_rank": 611,
        "cefr": "A1",
        "example": {
          "target": "Siéntese, señor.",
          "en": "Have a seat, sir."
        }
      },
      "distractors": [
        {
          "lemma": "amigo",
          "translation": "Friend",
          "gender": "m"
        },
        {
          "lemma": "señorita",
          "translation": "Miss",
          "gender": "f"
        },
        {
          "lemma": "señora",
          "translation": "Ma'am",
          "gender": "f"
        }
      ]
    },
    "block-es-a1-senora-001": {
      "id": "block-es-a1-senora-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 25,
      "content": "“señora” — ma'am, or Mrs. before a name. The respectful way to address or refer to a woman.",
      "learning_objective": "Learner recognizes and can use \"señora\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Señora is the polite word for a woman you just met — like your friend's mom.",
      "mnemonic": null,
      "usage_note": "Also doubles as a title before a surname, like “Mrs.” (señora García = Mrs. García). Like señor, it's simply the respectful, everyday term of address for a woman — not limited to older or married women.",
      "lang": {
        "lemma": "señora",
        "translation": "Ma'am",
        "pos": "n",
        "gender": "f",
        "ipa": "/seˈɲo.ɾa/",
        "audio": "audio/senora-001-lemma.mp3",
        "audio_example": "audio/senora-001-example.mp3",
        "freq_rank": 1446,
        "cefr": "A1",
        "example": {
          "target": "Buenas tardes, señora.",
          "en": "Good afternoon, ma'am."
        }
      },
      "distractors": [
        {
          "lemma": "señorita",
          "translation": "Miss",
          "gender": "f"
        },
        {
          "lemma": "amiga",
          "translation": "Friend",
          "gender": "f"
        },
        {
          "lemma": "amigo",
          "translation": "Friend",
          "gender": "m"
        }
      ]
    },
    "block-es-a1-senorita-001": {
      "id": "block-es-a1-senorita-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-04-amigos-personas",
      "dotted_id": "1.4",
      "order_index": 26,
      "content": "“señorita” — miss. The respectful way to address or refer to a young or unmarried woman.",
      "learning_objective": "Learner recognizes and can use \"señorita\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Señorita is the polite word for a young woman or girl you just met — like an older cousin or a babysitter.",
      "mnemonic": null,
      "usage_note": "Traditionally used for an unmarried or younger woman, similar to English “Miss.” Some speakers now avoid it with adult women for the same reason many English speakers now prefer “Ms.” over “Miss” — señora is a safer default with an adult stranger whose marital status you don't know.",
      "lang": {
        "lemma": "señorita",
        "translation": "Miss",
        "pos": "n",
        "gender": "f",
        "ipa": "/seɲoˈɾi.ta/",
        "audio": "audio/senorita-001-lemma.mp3",
        "audio_example": "audio/senorita-001-example.mp3",
        "freq_rank": 3032,
        "cefr": "A1",
        "example": {
          "target": "Gracias, señorita.",
          "en": "Thank you, miss."
        }
      },
      "distractors": [
        {
          "lemma": "amiga",
          "translation": "Friend",
          "gender": "f"
        },
        {
          "lemma": "señora",
          "translation": "Ma'am",
          "gender": "f"
        },
        {
          "lemma": "amigo",
          "translation": "Friend",
          "gender": "m"
        }
      ]
    },
    "block-es-a1-por-favor-001": {
      "id": "block-es-a1-por-favor-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 27,
      "content": "“por favor” — please. Tack it onto any request to make it polite.",
      "learning_objective": "Learner recognizes and can use \"por favor\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Por favor means “please” — the magic word for asking nicely.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "por favor",
        "translation": "Please",
        "pos": "interj",
        "gender": null,
        "ipa": "/poɾ faˈβoɾ/",
        "audio": "audio/por-favor-001-lemma.mp3",
        "audio_example": "audio/por-favor-001-example.mp3",
        "freq_rank": 98,
        "cefr": "A1",
        "example": {
          "target": "Un momento, por favor.",
          "en": "One moment, please."
        }
      },
      "distractors": [
        {
          "lemma": "perdón",
          "translation": "Sorry",
          "gender": null
        },
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "hasta luego",
          "translation": "See you",
          "gender": null
        }
      ]
    },
    "block-es-a1-gracias-001": {
      "id": "block-es-a1-gracias-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 28,
      "content": "“gracias” — thanks. One of the most useful words in the unit — use it constantly.",
      "learning_objective": "Learner recognizes and can use \"gracias\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Gracias means “thank you” — say it any time someone's kind to you.",
      "mnemonic": "Gracias and the English word “grace” both come from the same Latin root (gratia) — saying gracias is literally saying “graces.”",
      "usage_note": null,
      "lang": {
        "lemma": "gracias",
        "translation": "Thanks",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈɡɾa.sjas/",
        "audio": "audio/gracias-001-lemma.mp3",
        "audio_example": "audio/gracias-001-example.mp3",
        "freq_rank": 292,
        "cefr": "A1",
        "example": {
          "target": "¡Muchas gracias!",
          "en": "Thank you very much!"
        }
      },
      "distractors": [
        {
          "lemma": "hasta luego",
          "translation": "See you",
          "gender": null
        },
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        },
        {
          "lemma": "hasta mañana",
          "translation": "See you tomorrow",
          "gender": null
        }
      ]
    },
    "block-es-a1-de-nada-001": {
      "id": "block-es-a1-de-nada-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 29,
      "content": "“de nada” — you're welcome. The standard reply to gracias.",
      "learning_objective": "Learner recognizes and can use \"de nada\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "De nada means “you're welcome” — what you say back after someone says gracias.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "de nada",
        "translation": "You're welcome",
        "pos": "interj",
        "gender": null,
        "ipa": "/de ˈna.ða/",
        "audio": "audio/de-nada-001-lemma.mp3",
        "audio_example": "audio/de-nada-001-example.mp3",
        "freq_rank": 10389,
        "cefr": "A1",
        "example": {
          "target": "¡De nada, Jack!",
          "en": "You're welcome, Jack!"
        }
      },
      "distractors": [
        {
          "lemma": "lo siento",
          "translation": "Sorry",
          "gender": null
        },
        {
          "lemma": "hasta mañana",
          "translation": "See you tomorrow",
          "gender": null
        },
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        }
      ]
    },
    "block-es-a1-lo-siento-001": {
      "id": "block-es-a1-lo-siento-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 30,
      "content": "“lo siento” — I'm sorry. Reserved for sincere apologies, not small bumps: ¡Lo siento mucho! = I'm really sorry!",
      "learning_objective": "Learner recognizes and can use \"lo siento\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Lo siento means “I'm sorry” — save it for when something really needs an apology, like if you bump someone hard.",
      "mnemonic": null,
      "usage_note": "Reserved for sincere regret — a real apology for something that actually affected someone. Not used for bumping into someone in a hallway; reach for perdón or disculpe for the small stuff.",
      "lang": {
        "lemma": "lo siento",
        "translation": "Sorry",
        "pos": "interj",
        "gender": null,
        "ipa": "/lo ˈsjen.to/",
        "audio": "audio/lo-siento-001-lemma.mp3",
        "audio_example": "audio/lo-siento-001-example.mp3",
        "freq_rank": 1077,
        "cefr": "A1",
        "example": {
          "target": "¡Lo siento mucho!",
          "en": "I'm really sorry!"
        }
      },
      "distractors": [
        {
          "lemma": "gracias",
          "translation": "Thanks",
          "gender": null
        },
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        },
        {
          "lemma": "buenas noches",
          "translation": "Goodnight",
          "gender": null
        }
      ]
    },
    "block-es-a1-perdon-001": {
      "id": "block-es-a1-perdon-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 31,
      "content": "“perdón” — sorry / pardon me. A quick, flexible apology or attention-getter, lighter than lo siento.",
      "learning_objective": "Learner recognizes and can use \"perdón\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Perdón is a quick “sorry” or “pardon me” for little things, like a small bump.",
      "mnemonic": null,
      "usage_note": "A quick, all-purpose “sorry” or “pardon me,” lighter and more flexible in register than disculpe. Disculpe is grammatically fixed to the usted command form of disculpar, which is why it reads more formal; perdón is a noun (“pardon”) used as an exclamation, not tied to one grammatical person, so it moves more easily between casual and polite settings. Reach for lo siento when the apology is sincere and heavier.",
      "lang": {
        "lemma": "perdón",
        "translation": "Sorry",
        "pos": "interj",
        "gender": null,
        "ipa": "/peɾˈðon/",
        "audio": "audio/perdon-001-lemma.mp3",
        "audio_example": "audio/perdon-001-example.mp3",
        "freq_rank": 2293,
        "cefr": "A1",
        "example": {
          "target": "¡Ay, perdón!",
          "en": "Oops, sorry!"
        }
      },
      "distractors": [
        {
          "lemma": "hola",
          "translation": "Hi",
          "gender": null
        },
        {
          "lemma": "buenas noches",
          "translation": "Goodnight",
          "gender": null
        },
        {
          "lemma": "lo siento",
          "translation": "Sorry",
          "gender": null
        }
      ]
    },
    "block-es-a1-disculpe-001": {
      "id": "block-es-a1-disculpe-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-05-cortesia",
      "dotted_id": "1.5",
      "order_index": 32,
      "content": "“disculpe” — excuse me / I'm sorry. Covers both getting someone's attention and apologizing: Disculpe la tardanza. = I'm sorry I'm late.",
      "learning_objective": "Learner recognizes and can use \"disculpe\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Disculpe is a polite way to get someone's attention, or to say sorry for something small — like squeezing past someone.",
      "mnemonic": null,
      "usage_note": "Covers two speech acts: getting someone's polite attention (like tapping a stranger's shoulder) and apologizing (its example here: Disculpe la tardanza. = “I'm sorry I'm late.”). It's grammatically the usted (formal) command form of disculpar (“to excuse”) — that's why it defaults formal, not just convention.",
      "lang": {
        "lemma": "disculpe",
        "translation": "Excuse me",
        "pos": "interj",
        "gender": null,
        "ipa": "/disˈkul.pe/",
        "audio": "audio/disculpe-001-lemma.mp3",
        "audio_example": "audio/disculpe-001-example.mp3",
        "freq_rank": 1836,
        "cefr": "A1",
        "example": {
          "target": "Disculpe la tardanza.",
          "en": "I'm sorry I'm late."
        }
      },
      "distractors": [
        {
          "lemma": "adiós",
          "translation": "Bye",
          "gender": null
        },
        {
          "lemma": "por favor",
          "translation": "Please",
          "gender": null
        },
        {
          "lemma": "buenas tardes",
          "translation": "Good afternoon",
          "gender": null
        }
      ]
    },
    "block-es-a1-adios-001": {
      "id": "block-es-a1-adios-001",
      "type": "vocab",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-06-adios",
      "dotted_id": "1.6",
      "order_index": 33,
      "content": "“adiós” — bye. The standard farewell — works in almost any situation.",
      "learning_objective": "Learner recognizes and can use \"adiós\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Adiós means “bye!” — say it when it's time to head home.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "adiós",
        "translation": "Bye",
        "pos": "interj",
        "gender": null,
        "ipa": "/aˈðjos/",
        "audio": "audio/adios-001-lemma.mp3",
        "audio_example": "audio/adios-001-example.mp3",
        "freq_rank": 2210,
        "cefr": "A1",
        "example": {
          "target": "¡Adiós, amigo!",
          "en": "Bye, my friend!"
        }
      },
      "distractors": [
        {
          "lemma": "buenas noches",
          "translation": "Goodnight",
          "gender": null
        },
        {
          "lemma": "buenos días",
          "translation": "Good morning",
          "gender": null
        },
        {
          "lemma": "buenas tardes",
          "translation": "Good afternoon",
          "gender": null
        }
      ]
    },
    "block-es-a1-hasta-luego-001": {
      "id": "block-es-a1-hasta-luego-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-06-adios",
      "dotted_id": "1.6",
      "order_index": 34,
      "content": "“hasta luego” — see you later. A casual, open-ended farewell — no set time attached.",
      "learning_objective": "Learner recognizes and can use \"hasta luego\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Hasta luego means “see you later” — a friendly way to say bye for now.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "hasta luego",
        "translation": "See you",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈas.ta ˈlwe.ɣo/",
        "audio": "audio/hasta-luego-001-lemma.mp3",
        "audio_example": "audio/hasta-luego-001-example.mp3",
        "freq_rank": 16618,
        "cefr": "A1",
        "example": {
          "target": "Hasta luego, Tom.",
          "en": "See you later, Tom."
        }
      },
      "distractors": [
        {
          "lemma": "mucho gusto",
          "translation": "Nice to meet you",
          "gender": null
        },
        {
          "lemma": "de nada",
          "translation": "You're welcome",
          "gender": null
        },
        {
          "lemma": "lo siento",
          "translation": "Sorry",
          "gender": null
        }
      ]
    },
    "block-es-a1-hasta-pronto-001": {
      "id": "block-es-a1-hasta-pronto-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-06-adios",
      "dotted_id": "1.6",
      "order_index": 35,
      "content": "“hasta pronto” — see you soon. A warmer, more specific farewell than hasta luego.",
      "learning_objective": "Learner recognizes and can use \"hasta pronto\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Hasta pronto means “see you soon!”",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "hasta pronto",
        "translation": "See you soon",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈas.ta ˈpɾon.to/",
        "audio": "audio/hasta-pronto-001-lemma.mp3",
        "audio_example": "audio/hasta-pronto-001-example.mp3",
        "freq_rank": 34899,
        "cefr": "A1",
        "example": {
          "target": "Hasta pronto.",
          "en": "See you soon."
        }
      },
      "distractors": [
        {
          "lemma": "hasta luego",
          "translation": "See you",
          "gender": null
        },
        {
          "lemma": "gracias",
          "translation": "Thanks",
          "gender": null
        },
        {
          "lemma": "de nada",
          "translation": "You're welcome",
          "gender": null
        }
      ]
    },
    "block-es-a1-hasta-manana-001": {
      "id": "block-es-a1-hasta-manana-001",
      "type": "phrase",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-06-adios",
      "dotted_id": "1.6",
      "order_index": 36,
      "content": "“hasta mañana” — see you tomorrow. Use it when you know you'll cross paths again the next day.",
      "learning_objective": "Learner recognizes and can use \"hasta mañana\".",
      "difficulty": 1,
      "audience": "both",
      "flashcard": true,
      "games": [
        "matching"
      ],
      "kid_track": "Hasta mañana means “see you tomorrow” — for a friend you'll see again the next day.",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "hasta mañana",
        "translation": "See you tomorrow",
        "pos": "interj",
        "gender": null,
        "ipa": "/ˈas.ta maˈɲa.na/",
        "audio": "audio/hasta-manana-001-lemma.mp3",
        "audio_example": "audio/hasta-manana-001-example.mp3",
        "freq_rank": 28575,
        "cefr": "A1",
        "example": {
          "target": "Hasta mañana.",
          "en": "See you again tomorrow."
        }
      },
      "distractors": [
        {
          "lemma": "buenas noches",
          "translation": "Goodnight",
          "gender": null
        },
        {
          "lemma": "adiós",
          "translation": "Bye",
          "gender": null
        },
        {
          "lemma": "hola",
          "translation": "Hi",
          "gender": null
        }
      ]
    },
    "block-es-a1-capstone-nuevo-amigo-001": {
      "id": "block-es-a1-capstone-nuevo-amigo-001",
      "type": "dialogue",
      "unit_id": "unit-1-saludos",
      "lesson_id": "lesson-saludos-06-adios",
      "dotted_id": "1.6",
      "order_index": 37,
      "content": "Put every piece of this unit together: greet a new friend, ask how they are, trade names, say it's nice to meet them, and say goodbye. Read it out loud with your grown-up, one part each, then switch roles. Two new little words show up here too: también = too, and bueno = well. (¿Y tú? isn't a new word either -- it's just y (and) + tú (you), which you already know.)",
      "learning_objective": "Learner produces the full greet → ask-how-are-you → trade-names → nice-to-meet-you → farewell exchange as one rehearsable dialogue, anchored on the spine phrase ¿Cómo te llamas? / Me llamo…",
      "difficulty": 2,
      "audience": "both",
      "flashcard": false,
      "games": [
        "ordering"
      ],
      "kid_track": "This is the whole conversation, from hello to goodbye! Have your grown-up read Diego's lines, and you read Sofía's lines — then switch! ¿Cómo te llamas? (What's your name?) and Me llamo... (My name is...) are the most important line to remember — you'll use them every time you meet someone new. Two brand-new tiny words show up here: también means “too,” and bueno means “well” (like when you're about to say something next). Plus a fun discovery: you already know tú — ¿Y tú? is really just y (and) + tú (you) stuck together!",
      "mnemonic": null,
      "usage_note": null,
      "lang": {
        "lemma": "diálogo: un nuevo amigo",
        "translation": "Dialogue: meeting a new friend",
        "pos": null,
        "gender": null,
        "ipa": null,
        "audio": "audio/capstone-nuevo-amigo-001.mp3",
        "audio_example": "audio/capstone-nuevo-amigo-001.mp3",
        "freq_rank": null,
        "cefr": "A1",
        "example": {
          "target": "A: ¡Hola!\nB: ¡Hola! ¿Cómo estás?\nA: Bien, gracias. ¿Y tú?\nB: Bien también. ¿Cómo te llamas?\nA: Me llamo Diego. ¿Y tú?\nB: Me llamo Sofía. ¡Mucho gusto!\nA: ¡Encantado! Bueno... ¡adiós!\nB: ¡Adiós! Hasta luego.",
          "en": "A: Hi!\nB: Hi! How are you?\nA: Fine, thanks. And you?\nB: Fine too. What's your name?\nA: My name's Diego. And you?\nB: My name's Sofía. Nice to meet you!\nA: Nice to meet you too! Well... bye!\nB: Bye! See you later."
        }
      },
      "distractors": [],
      "dialogue_turns": [
        {
          "speaker": "A",
          "target": "¡Hola!",
          "en": "Hi!"
        },
        {
          "speaker": "B",
          "target": "¡Hola! ¿Cómo estás?",
          "en": "Hi! How are you?"
        },
        {
          "speaker": "A",
          "target": "Bien, gracias. ¿Y tú?",
          "en": "Fine, thanks. And you?"
        },
        {
          "speaker": "B",
          "target": "Bien también. ¿Cómo te llamas?",
          "en": "Fine too. What's your name?"
        },
        {
          "speaker": "A",
          "target": "Me llamo Diego. ¿Y tú?",
          "en": "My name's Diego. And you?"
        },
        {
          "speaker": "B",
          "target": "Me llamo Sofía. ¡Mucho gusto!",
          "en": "My name's Sofía. Nice to meet you!"
        },
        {
          "speaker": "A",
          "target": "¡Encantado! Bueno... ¡adiós!",
          "en": "Nice to meet you too! Well... bye!"
        },
        {
          "speaker": "B",
          "target": "¡Adiós! Hasta luego.",
          "en": "Bye! See you later."
        }
      ],
      "retrieval_game": {
        "id": "game-es-a1-capstone-nuevo-amigo-order-001",
        "type": "ordering",
        "data": {
          "steps": [
            "¡Hola!",
            "¡Hola! ¿Cómo estás?",
            "Bien, gracias. ¿Y tú?",
            "Bien también. ¿Cómo te llamas?",
            "Me llamo Diego. ¿Y tú?",
            "Me llamo Sofía. ¡Mucho gusto!",
            "¡Encantado! Bueno... ¡adiós!",
            "¡Adiós! Hasta luego."
          ]
        }
      }
    }
  },
  "teaching_order": [
    "block-es-a1-hola-001",
    "block-es-a1-si-001",
    "block-es-a1-no-001",
    "block-es-a1-buenos-dias-001",
    "block-es-a1-buenas-tardes-001",
    "block-es-a1-buenas-noches-001",
    "block-es-a1-pattern-greetings-time-001",
    "block-es-a1-como-001",
    "block-es-a1-que-001",
    "block-es-a1-bien-001",
    "block-es-a1-mal-001",
    "block-es-a1-mas-o-menos-001",
    "block-es-a1-y-tu-001",
    "block-es-a1-yo-001",
    "block-es-a1-tu-001",
    "block-es-a1-ser-001",
    "block-es-a1-llamarse-001",
    "block-es-a1-mucho-gusto-001",
    "block-es-a1-encantado-001",
    "block-es-a1-encantada-001",
    "block-es-a1-amigo-001",
    "block-es-a1-amiga-001",
    "block-es-a1-pattern-gender-oa-001",
    "block-es-a1-usted-001",
    "block-es-a1-senor-001",
    "block-es-a1-senora-001",
    "block-es-a1-senorita-001",
    "block-es-a1-por-favor-001",
    "block-es-a1-gracias-001",
    "block-es-a1-de-nada-001",
    "block-es-a1-lo-siento-001",
    "block-es-a1-perdon-001",
    "block-es-a1-disculpe-001",
    "block-es-a1-adios-001",
    "block-es-a1-hasta-luego-001",
    "block-es-a1-hasta-pronto-001",
    "block-es-a1-hasta-manana-001",
    "block-es-a1-capstone-nuevo-amigo-001"
  ],
  "leitner_card_ids": [
    "block-es-a1-hola-001",
    "block-es-a1-si-001",
    "block-es-a1-no-001",
    "block-es-a1-buenos-dias-001",
    "block-es-a1-buenas-tardes-001",
    "block-es-a1-buenas-noches-001",
    "block-es-a1-como-001",
    "block-es-a1-que-001",
    "block-es-a1-bien-001",
    "block-es-a1-mal-001",
    "block-es-a1-mas-o-menos-001",
    "block-es-a1-y-tu-001",
    "block-es-a1-yo-001",
    "block-es-a1-tu-001",
    "block-es-a1-ser-001",
    "block-es-a1-llamarse-001",
    "block-es-a1-mucho-gusto-001",
    "block-es-a1-encantado-001",
    "block-es-a1-encantada-001",
    "block-es-a1-amigo-001",
    "block-es-a1-amiga-001",
    "block-es-a1-usted-001",
    "block-es-a1-senor-001",
    "block-es-a1-senora-001",
    "block-es-a1-senorita-001",
    "block-es-a1-por-favor-001",
    "block-es-a1-gracias-001",
    "block-es-a1-de-nada-001",
    "block-es-a1-lo-siento-001",
    "block-es-a1-perdon-001",
    "block-es-a1-disculpe-001",
    "block-es-a1-adios-001",
    "block-es-a1-hasta-luego-001",
    "block-es-a1-hasta-pronto-001",
    "block-es-a1-hasta-manana-001"
  ],
  "capstone_block_id": "block-es-a1-capstone-nuevo-amigo-001",
  "audio_manifest": {
    "block-es-a1-hola-001": "audio/hola-001-lemma.mp3",
    "block-es-a1-si-001": "audio/si-001-lemma.mp3",
    "block-es-a1-no-001": "audio/no-001-lemma.mp3",
    "block-es-a1-buenos-dias-001": "audio/buenos-dias-001-lemma.mp3",
    "block-es-a1-buenas-tardes-001": "audio/buenas-tardes-001-lemma.mp3",
    "block-es-a1-buenas-noches-001": "audio/buenas-noches-001-lemma.mp3",
    "block-es-a1-como-001": "audio/como-001-lemma.mp3",
    "block-es-a1-que-001": "audio/que-001-lemma.mp3",
    "block-es-a1-bien-001": "audio/bien-001-lemma.mp3",
    "block-es-a1-mal-001": "audio/mal-001-lemma.mp3",
    "block-es-a1-mas-o-menos-001": "audio/mas-o-menos-001-lemma.mp3",
    "block-es-a1-y-tu-001": "audio/y-tu-001-lemma.mp3",
    "block-es-a1-yo-001": "audio/yo-001-lemma.mp3",
    "block-es-a1-tu-001": "audio/tu-001-lemma.mp3",
    "block-es-a1-ser-001": "audio/ser-001-lemma.mp3",
    "block-es-a1-llamarse-001": "audio/llamarse-001-lemma.mp3",
    "block-es-a1-mucho-gusto-001": "audio/mucho-gusto-001-lemma.mp3",
    "block-es-a1-encantado-001": "audio/encantado-001-lemma.mp3",
    "block-es-a1-encantada-001": "audio/encantada-001-lemma.mp3",
    "block-es-a1-amigo-001": "audio/amigo-001-lemma.mp3",
    "block-es-a1-amiga-001": "audio/amiga-001-lemma.mp3",
    "block-es-a1-usted-001": "audio/usted-001-lemma.mp3",
    "block-es-a1-senor-001": "audio/senor-001-lemma.mp3",
    "block-es-a1-senora-001": "audio/senora-001-lemma.mp3",
    "block-es-a1-senorita-001": "audio/senorita-001-lemma.mp3",
    "block-es-a1-por-favor-001": "audio/por-favor-001-lemma.mp3",
    "block-es-a1-gracias-001": "audio/gracias-001-lemma.mp3",
    "block-es-a1-de-nada-001": "audio/de-nada-001-lemma.mp3",
    "block-es-a1-lo-siento-001": "audio/lo-siento-001-lemma.mp3",
    "block-es-a1-perdon-001": "audio/perdon-001-lemma.mp3",
    "block-es-a1-disculpe-001": "audio/disculpe-001-lemma.mp3",
    "block-es-a1-adios-001": "audio/adios-001-lemma.mp3",
    "block-es-a1-hasta-luego-001": "audio/hasta-luego-001-lemma.mp3",
    "block-es-a1-hasta-pronto-001": "audio/hasta-pronto-001-lemma.mp3",
    "block-es-a1-hasta-manana-001": "audio/hasta-manana-001-lemma.mp3",
    "block-es-a1-capstone-nuevo-amigo-001": "audio/capstone-nuevo-amigo-001.mp3"
  },
  "generated": {
    "from": "blocks.json",
    "at": "2026-07-02T08:44:59.866Z",
    "block_count": 38,
    "lesson_count": 6,
    "leitner_card_count": 35
  }
};
